# Generated by Django 4.2.13 on 2024-06-13 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_notification_donor_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
