# Generated by Django 4.2.13 on 2024-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_badge_delete_reward_remove_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='main.badge'),
        ),
    ]
