# Generated by Django 4.2.13 on 2024-06-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_badge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='tier',
        ),
    ]
