# Generated by Django 4.2.13 on 2024-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_badge_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default=None, max_length=10),
        ),
    ]
