# Generated by Django 4.2.13 on 2024-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_badge_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=10, unique=True),
        ),
    ]
