# Generated by Django 4.2.13 on 2024-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_badge_name_alter_badge_tier_successstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
