# Generated by Django 4.2.13 on 2024-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
